//  Source: lemmy/crates/api_common/src/websocket/handlers/captcha.rs
// Code generated by go.elara.ws/go-lemmy/cmd/gen (struct generator). DO NOT EDIT.

package types

type AddCaptcha struct {
	Captcha CaptchaItem `json:"captcha" url:"captcha,omitempty"`
}
type CheckCaptcha struct {
	Uuid   string `json:"uuid" url:"uuid,omitempty"`
	Answer string `json:"answer" url:"answer,omitempty"`
}
