//  Source: lemmy/crates/api_common/src/websocket/handlers/connect.rs
// Code generated by go.elara.ws/go-lemmy/cmd/gen (struct generator). DO NOT EDIT.

package types

type Disconnect struct {
	ID int `json:"id" url:"id,omitempty"`
}
