//  Source: lemmy/crates/api_common/src/custom_emoji.rs
// Code generated by go.elara.ws/go-lemmy/cmd/gen (struct generator). DO NOT EDIT.

package types

type CreateCustomEmoji struct {
	Category  string   `json:"category" url:"category,omitempty"`
	Shortcode string   `json:"shortcode" url:"shortcode,omitempty"`
	ImageURL  string   `json:"image_url" url:"image_url,omitempty"`
	AltText   string   `json:"alt_text" url:"alt_text,omitempty"`
	Keywords  []string `json:"keywords" url:"keywords,omitempty"`
	Auth      string   `json:"auth" url:"auth,omitempty"`
}
type EditCustomEmoji struct {
	ID       int      `json:"id" url:"id,omitempty"`
	Category string   `json:"category" url:"category,omitempty"`
	ImageURL string   `json:"image_url" url:"image_url,omitempty"`
	AltText  string   `json:"alt_text" url:"alt_text,omitempty"`
	Keywords []string `json:"keywords" url:"keywords,omitempty"`
	Auth     string   `json:"auth" url:"auth,omitempty"`
}
type DeleteCustomEmoji struct {
	ID   int    `json:"id" url:"id,omitempty"`
	Auth string `json:"auth" url:"auth,omitempty"`
}
type DeleteCustomEmojiResponse struct {
	ID      int  `json:"id" url:"id,omitempty"`
	Success bool `json:"success" url:"success,omitempty"`
	LemmyResponse
}
type CustomEmojiResponse struct {
	CustomEmoji CustomEmojiView `json:"custom_emoji" url:"custom_emoji,omitempty"`
	LemmyResponse
}
