//  Source: lemmy/crates/db_schema/src/source/custom_emoji_keyword.rs
// Code generated by go.elara.ws/go-lemmy/cmd/gen (struct generator). DO NOT EDIT.

package types

type CustomEmojiKeyword struct {
	ID            int32  `json:"id" url:"id,omitempty"`
	CustomEmojiID int    `json:"custom_emoji_id" url:"custom_emoji_id,omitempty"`
	Keyword       string `json:"keyword" url:"keyword,omitempty"`
}
type CustomEmojiKeywordInsertForm struct {
	CustomEmojiID int    `json:"custom_emoji_id" url:"custom_emoji_id,omitempty"`
	Keyword       string `json:"keyword" url:"keyword,omitempty"`
}
