//  Source: lemmy/crates/db_schema/src/source/custom_emoji.rs
// Code generated by go.elara.ws/go-lemmy/cmd/gen (struct generator). DO NOT EDIT.

package types

type CustomEmoji struct {
	ID          int       `json:"id" url:"id,omitempty"`
	LocalSiteID int       `json:"local_site_id" url:"local_site_id,omitempty"`
	Shortcode   string    `json:"shortcode" url:"shortcode,omitempty"`
	ImageURL    string    `json:"image_url" url:"image_url,omitempty"`
	AltText     string    `json:"alt_text" url:"alt_text,omitempty"`
	Category    string    `json:"category" url:"category,omitempty"`
	Published   LemmyTime `json:"published" url:"published,omitempty"`
	Updated     LemmyTime `json:"updated" url:"updated,omitempty"`
}
type CustomEmojiInsertForm struct {
	LocalSiteID int    `json:"local_site_id" url:"local_site_id,omitempty"`
	Shortcode   string `json:"shortcode" url:"shortcode,omitempty"`
	ImageURL    string `json:"image_url" url:"image_url,omitempty"`
	AltText     string `json:"alt_text" url:"alt_text,omitempty"`
	Category    string `json:"category" url:"category,omitempty"`
}
type CustomEmojiUpdateForm struct {
	LocalSiteID int    `json:"local_site_id" url:"local_site_id,omitempty"`
	ImageURL    string `json:"image_url" url:"image_url,omitempty"`
	AltText     string `json:"alt_text" url:"alt_text,omitempty"`
	Category    string `json:"category" url:"category,omitempty"`
}
