//  Source: lemmy/crates/db_schema/src/source/federation_allowlist.rs
// Code generated by go.elara.ws/go-lemmy/cmd/gen (struct generator). DO NOT EDIT.

package types

type FederationAllowList struct {
	ID         int32     `json:"id" url:"id,omitempty"`
	InstanceID int       `json:"instance_id" url:"instance_id,omitempty"`
	Published  LemmyTime `json:"published" url:"published,omitempty"`
	Updated    LemmyTime `json:"updated" url:"updated,omitempty"`
}
type FederationAllowListForm struct {
	InstanceID int       `json:"instance_id" url:"instance_id,omitempty"`
	Updated    LemmyTime `json:"updated" url:"updated,omitempty"`
}
