//  Source: lemmy/crates/db_schema/src/source/instance.rs
// Code generated by go.arsenm.dev/go-lemmy/cmd/gen (struct generator). DO NOT EDIT.

package types

type Instance struct {
	ID        int       `json:"id" url:"id,omitempty"`
	Domain    string    `json:"domain" url:"domain,omitempty"`
	Published LemmyTime `json:"published" url:"published,omitempty"`
	Updated   LemmyTime `json:"updated" url:"updated,omitempty"`
}
type InstanceForm struct {
	Domain  string    `json:"domain" url:"domain,omitempty"`
	Updated LemmyTime `json:"updated" url:"updated,omitempty"`
}
