//  Source: lemmy/crates/api_common/src/websocket/handlers/join_rooms.rs
// Code generated by go.elara.ws/go-lemmy/cmd/gen (struct generator). DO NOT EDIT.

package types

type JoinPostRoom struct {
	PostID int `json:"post_id" url:"post_id,omitempty"`
	ID     int `json:"id" url:"id,omitempty"`
}
type JoinCommunityRoom struct {
	CommunityID int `json:"community_id" url:"community_id,omitempty"`
	ID          int `json:"id" url:"id,omitempty"`
}
type JoinModRoom struct {
	CommunityID int `json:"community_id" url:"community_id,omitempty"`
	ID          int `json:"id" url:"id,omitempty"`
}
type JoinUserRoom struct {
	UserID int `json:"user_id" url:"user_id,omitempty"`
	ID     int `json:"id" url:"id,omitempty"`
}
