//  Source: lemmy/crates/db_schema/src/source/local_site_rate_limit.rs
// Code generated by go.elara.ws/go-lemmy/cmd/gen (struct generator). DO NOT EDIT.

package types

type LocalSiteRateLimit struct {
	ID                int32     `json:"id" url:"id,omitempty"`
	LocalSiteID       int       `json:"local_site_id" url:"local_site_id,omitempty"`
	Message           int32     `json:"message" url:"message,omitempty"`
	MessagePerSecond  int32     `json:"message_per_second" url:"message_per_second,omitempty"`
	Post              int32     `json:"post" url:"post,omitempty"`
	PostPerSecond     int32     `json:"post_per_second" url:"post_per_second,omitempty"`
	Register          int32     `json:"register" url:"register,omitempty"`
	RegisterPerSecond int32     `json:"register_per_second" url:"register_per_second,omitempty"`
	Image             int32     `json:"image" url:"image,omitempty"`
	ImagePerSecond    int32     `json:"image_per_second" url:"image_per_second,omitempty"`
	Comment           int32     `json:"comment" url:"comment,omitempty"`
	CommentPerSecond  int32     `json:"comment_per_second" url:"comment_per_second,omitempty"`
	Search            int32     `json:"search" url:"search,omitempty"`
	SearchPerSecond   int32     `json:"search_per_second" url:"search_per_second,omitempty"`
	Published         LemmyTime `json:"published" url:"published,omitempty"`
	Updated           LemmyTime `json:"updated" url:"updated,omitempty"`
}
type LocalSiteRateLimitInsertForm struct {
	LocalSiteID       int             `json:"local_site_id" url:"local_site_id,omitempty"`
	Message           Optional[int32] `json:"message" url:"message,omitempty"`
	MessagePerSecond  Optional[int32] `json:"message_per_second" url:"message_per_second,omitempty"`
	Post              Optional[int32] `json:"post" url:"post,omitempty"`
	PostPerSecond     Optional[int32] `json:"post_per_second" url:"post_per_second,omitempty"`
	Register          Optional[int32] `json:"register" url:"register,omitempty"`
	RegisterPerSecond Optional[int32] `json:"register_per_second" url:"register_per_second,omitempty"`
	Image             Optional[int32] `json:"image" url:"image,omitempty"`
	ImagePerSecond    Optional[int32] `json:"image_per_second" url:"image_per_second,omitempty"`
	Comment           Optional[int32] `json:"comment" url:"comment,omitempty"`
	CommentPerSecond  Optional[int32] `json:"comment_per_second" url:"comment_per_second,omitempty"`
	Search            Optional[int32] `json:"search" url:"search,omitempty"`
	SearchPerSecond   Optional[int32] `json:"search_per_second" url:"search_per_second,omitempty"`
}
type LocalSiteRateLimitUpdateForm struct {
	Message           Optional[int32] `json:"message" url:"message,omitempty"`
	MessagePerSecond  Optional[int32] `json:"message_per_second" url:"message_per_second,omitempty"`
	Post              Optional[int32] `json:"post" url:"post,omitempty"`
	PostPerSecond     Optional[int32] `json:"post_per_second" url:"post_per_second,omitempty"`
	Register          Optional[int32] `json:"register" url:"register,omitempty"`
	RegisterPerSecond Optional[int32] `json:"register_per_second" url:"register_per_second,omitempty"`
	Image             Optional[int32] `json:"image" url:"image,omitempty"`
	ImagePerSecond    Optional[int32] `json:"image_per_second" url:"image_per_second,omitempty"`
	Comment           Optional[int32] `json:"comment" url:"comment,omitempty"`
	CommentPerSecond  Optional[int32] `json:"comment_per_second" url:"comment_per_second,omitempty"`
	Search            Optional[int32] `json:"search" url:"search,omitempty"`
	SearchPerSecond   Optional[int32] `json:"search_per_second" url:"search_per_second,omitempty"`
	Updated           LemmyTime       `json:"updated" url:"updated,omitempty"`
}
