//  Source: lemmy/crates/api_common/src/websocket/handlers/messages.rs
// Code generated by go.elara.ws/go-lemmy/cmd/gen (struct generator). DO NOT EDIT.

package types

type SendPostRoomMessage struct {
	PostID      int           `json:"post_id" url:"post_id,omitempty"`
	Message     string        `json:"message" url:"message,omitempty"`
	WebsocketID Optional[int] `json:"websocket_id" url:"websocket_id,omitempty"`
}
type SendCommunityRoomMessage struct {
	CommunityID int           `json:"community_id" url:"community_id,omitempty"`
	Message     string        `json:"message" url:"message,omitempty"`
	WebsocketID Optional[int] `json:"websocket_id" url:"websocket_id,omitempty"`
}
type SendModRoomMessage struct {
	CommunityID int           `json:"community_id" url:"community_id,omitempty"`
	Message     string        `json:"message" url:"message,omitempty"`
	WebsocketID Optional[int] `json:"websocket_id" url:"websocket_id,omitempty"`
}
type SendUserRoomMessage struct {
	RecipientID int           `json:"recipient_id" url:"recipient_id,omitempty"`
	Message     string        `json:"message" url:"message,omitempty"`
	WebsocketID Optional[int] `json:"websocket_id" url:"websocket_id,omitempty"`
}
type SendAllMessage struct {
	Message     string        `json:"message" url:"message,omitempty"`
	WebsocketID Optional[int] `json:"websocket_id" url:"websocket_id,omitempty"`
}
