//  Source: lemmy/crates/db_schema/src/source/moderator.rs
// Code generated by go.elara.ws/go-lemmy/cmd/gen (struct generator). DO NOT EDIT.

package types

type ModRemovePost struct {
	ID          int32            `json:"id" url:"id,omitempty"`
	ModPersonID int              `json:"mod_person_id" url:"mod_person_id,omitempty"`
	PostID      int              `json:"post_id" url:"post_id,omitempty"`
	Reason      Optional[string] `json:"reason" url:"reason,omitempty"`
	Removed     bool             `json:"removed" url:"removed,omitempty"`
	When        LemmyTime        `json:"when_" url:"when_,omitempty"`
}
type ModRemovePostForm struct {
	ModPersonID int              `json:"mod_person_id" url:"mod_person_id,omitempty"`
	PostID      int              `json:"post_id" url:"post_id,omitempty"`
	Reason      Optional[string] `json:"reason" url:"reason,omitempty"`
	Removed     Optional[bool]   `json:"removed" url:"removed,omitempty"`
}
type ModLockPost struct {
	ID          int32     `json:"id" url:"id,omitempty"`
	ModPersonID int       `json:"mod_person_id" url:"mod_person_id,omitempty"`
	PostID      int       `json:"post_id" url:"post_id,omitempty"`
	Locked      bool      `json:"locked" url:"locked,omitempty"`
	When        LemmyTime `json:"when_" url:"when_,omitempty"`
}
type ModLockPostForm struct {
	ModPersonID int            `json:"mod_person_id" url:"mod_person_id,omitempty"`
	PostID      int            `json:"post_id" url:"post_id,omitempty"`
	Locked      Optional[bool] `json:"locked" url:"locked,omitempty"`
}
type ModFeaturePost struct {
	ID                  int32     `json:"id" url:"id,omitempty"`
	ModPersonID         int       `json:"mod_person_id" url:"mod_person_id,omitempty"`
	PostID              int       `json:"post_id" url:"post_id,omitempty"`
	Featured            bool      `json:"featured" url:"featured,omitempty"`
	When                LemmyTime `json:"when_" url:"when_,omitempty"`
	IsFeaturedCommunity bool      `json:"is_featured_community" url:"is_featured_community,omitempty"`
}
type ModFeaturePostForm struct {
	ModPersonID         int  `json:"mod_person_id" url:"mod_person_id,omitempty"`
	PostID              int  `json:"post_id" url:"post_id,omitempty"`
	Featured            bool `json:"featured" url:"featured,omitempty"`
	IsFeaturedCommunity bool `json:"is_featured_community" url:"is_featured_community,omitempty"`
}
type ModRemoveComment struct {
	ID          int32            `json:"id" url:"id,omitempty"`
	ModPersonID int              `json:"mod_person_id" url:"mod_person_id,omitempty"`
	CommentID   int              `json:"comment_id" url:"comment_id,omitempty"`
	Reason      Optional[string] `json:"reason" url:"reason,omitempty"`
	Removed     bool             `json:"removed" url:"removed,omitempty"`
	When        LemmyTime        `json:"when_" url:"when_,omitempty"`
}
type ModRemoveCommentForm struct {
	ModPersonID int              `json:"mod_person_id" url:"mod_person_id,omitempty"`
	CommentID   int              `json:"comment_id" url:"comment_id,omitempty"`
	Reason      Optional[string] `json:"reason" url:"reason,omitempty"`
	Removed     Optional[bool]   `json:"removed" url:"removed,omitempty"`
}
type ModRemoveCommunity struct {
	ID          int32            `json:"id" url:"id,omitempty"`
	ModPersonID int              `json:"mod_person_id" url:"mod_person_id,omitempty"`
	CommunityID int              `json:"community_id" url:"community_id,omitempty"`
	Reason      Optional[string] `json:"reason" url:"reason,omitempty"`
	Removed     bool             `json:"removed" url:"removed,omitempty"`
	Expires     LemmyTime        `json:"expires" url:"expires,omitempty"`
	When        LemmyTime        `json:"when_" url:"when_,omitempty"`
}
type ModRemoveCommunityForm struct {
	ModPersonID int              `json:"mod_person_id" url:"mod_person_id,omitempty"`
	CommunityID int              `json:"community_id" url:"community_id,omitempty"`
	Reason      Optional[string] `json:"reason" url:"reason,omitempty"`
	Removed     Optional[bool]   `json:"removed" url:"removed,omitempty"`
	Expires     LemmyTime        `json:"expires" url:"expires,omitempty"`
}
type ModBanFromCommunity struct {
	ID            int32            `json:"id" url:"id,omitempty"`
	ModPersonID   int              `json:"mod_person_id" url:"mod_person_id,omitempty"`
	OtherPersonID int              `json:"other_person_id" url:"other_person_id,omitempty"`
	CommunityID   int              `json:"community_id" url:"community_id,omitempty"`
	Reason        Optional[string] `json:"reason" url:"reason,omitempty"`
	Banned        bool             `json:"banned" url:"banned,omitempty"`
	Expires       LemmyTime        `json:"expires" url:"expires,omitempty"`
	When          LemmyTime        `json:"when_" url:"when_,omitempty"`
}
type ModBanFromCommunityForm struct {
	ModPersonID   int              `json:"mod_person_id" url:"mod_person_id,omitempty"`
	OtherPersonID int              `json:"other_person_id" url:"other_person_id,omitempty"`
	CommunityID   int              `json:"community_id" url:"community_id,omitempty"`
	Reason        Optional[string] `json:"reason" url:"reason,omitempty"`
	Banned        Optional[bool]   `json:"banned" url:"banned,omitempty"`
	Expires       LemmyTime        `json:"expires" url:"expires,omitempty"`
}
type ModBan struct {
	ID            int32            `json:"id" url:"id,omitempty"`
	ModPersonID   int              `json:"mod_person_id" url:"mod_person_id,omitempty"`
	OtherPersonID int              `json:"other_person_id" url:"other_person_id,omitempty"`
	Reason        Optional[string] `json:"reason" url:"reason,omitempty"`
	Banned        bool             `json:"banned" url:"banned,omitempty"`
	Expires       LemmyTime        `json:"expires" url:"expires,omitempty"`
	When          LemmyTime        `json:"when_" url:"when_,omitempty"`
}
type ModHideCommunityForm struct {
	CommunityID int              `json:"community_id" url:"community_id,omitempty"`
	ModPersonID int              `json:"mod_person_id" url:"mod_person_id,omitempty"`
	Hidden      Optional[bool]   `json:"hidden" url:"hidden,omitempty"`
	Reason      Optional[string] `json:"reason" url:"reason,omitempty"`
}
type ModHideCommunity struct {
	ID          int32            `json:"id" url:"id,omitempty"`
	CommunityID int              `json:"community_id" url:"community_id,omitempty"`
	ModPersonID int              `json:"mod_person_id" url:"mod_person_id,omitempty"`
	When        LemmyTime        `json:"when_" url:"when_,omitempty"`
	Reason      Optional[string] `json:"reason" url:"reason,omitempty"`
	Hidden      bool             `json:"hidden" url:"hidden,omitempty"`
}
type ModBanForm struct {
	ModPersonID   int              `json:"mod_person_id" url:"mod_person_id,omitempty"`
	OtherPersonID int              `json:"other_person_id" url:"other_person_id,omitempty"`
	Reason        Optional[string] `json:"reason" url:"reason,omitempty"`
	Banned        Optional[bool]   `json:"banned" url:"banned,omitempty"`
	Expires       LemmyTime        `json:"expires" url:"expires,omitempty"`
}
type ModAddCommunity struct {
	ID            int32     `json:"id" url:"id,omitempty"`
	ModPersonID   int       `json:"mod_person_id" url:"mod_person_id,omitempty"`
	OtherPersonID int       `json:"other_person_id" url:"other_person_id,omitempty"`
	CommunityID   int       `json:"community_id" url:"community_id,omitempty"`
	Removed       bool      `json:"removed" url:"removed,omitempty"`
	When          LemmyTime `json:"when_" url:"when_,omitempty"`
}
type ModAddCommunityForm struct {
	ModPersonID   int            `json:"mod_person_id" url:"mod_person_id,omitempty"`
	OtherPersonID int            `json:"other_person_id" url:"other_person_id,omitempty"`
	CommunityID   int            `json:"community_id" url:"community_id,omitempty"`
	Removed       Optional[bool] `json:"removed" url:"removed,omitempty"`
}
type ModTransferCommunity struct {
	ID            int32     `json:"id" url:"id,omitempty"`
	ModPersonID   int       `json:"mod_person_id" url:"mod_person_id,omitempty"`
	OtherPersonID int       `json:"other_person_id" url:"other_person_id,omitempty"`
	CommunityID   int       `json:"community_id" url:"community_id,omitempty"`
	When          LemmyTime `json:"when_" url:"when_,omitempty"`
}
type ModTransferCommunityForm struct {
	ModPersonID   int `json:"mod_person_id" url:"mod_person_id,omitempty"`
	OtherPersonID int `json:"other_person_id" url:"other_person_id,omitempty"`
	CommunityID   int `json:"community_id" url:"community_id,omitempty"`
}
type ModAdd struct {
	ID            int32     `json:"id" url:"id,omitempty"`
	ModPersonID   int       `json:"mod_person_id" url:"mod_person_id,omitempty"`
	OtherPersonID int       `json:"other_person_id" url:"other_person_id,omitempty"`
	Removed       bool      `json:"removed" url:"removed,omitempty"`
	When          LemmyTime `json:"when_" url:"when_,omitempty"`
}
type ModAddForm struct {
	ModPersonID   int            `json:"mod_person_id" url:"mod_person_id,omitempty"`
	OtherPersonID int            `json:"other_person_id" url:"other_person_id,omitempty"`
	Removed       Optional[bool] `json:"removed" url:"removed,omitempty"`
}
type AdminPurgePerson struct {
	ID            int32            `json:"id" url:"id,omitempty"`
	AdminPersonID int              `json:"admin_person_id" url:"admin_person_id,omitempty"`
	Reason        Optional[string] `json:"reason" url:"reason,omitempty"`
	When          LemmyTime        `json:"when_" url:"when_,omitempty"`
}
type AdminPurgePersonForm struct {
	AdminPersonID int              `json:"admin_person_id" url:"admin_person_id,omitempty"`
	Reason        Optional[string] `json:"reason" url:"reason,omitempty"`
}
type AdminPurgeCommunity struct {
	ID            int32            `json:"id" url:"id,omitempty"`
	AdminPersonID int              `json:"admin_person_id" url:"admin_person_id,omitempty"`
	Reason        Optional[string] `json:"reason" url:"reason,omitempty"`
	When          LemmyTime        `json:"when_" url:"when_,omitempty"`
}
type AdminPurgeCommunityForm struct {
	AdminPersonID int              `json:"admin_person_id" url:"admin_person_id,omitempty"`
	Reason        Optional[string] `json:"reason" url:"reason,omitempty"`
}
type AdminPurgePost struct {
	ID            int32            `json:"id" url:"id,omitempty"`
	AdminPersonID int              `json:"admin_person_id" url:"admin_person_id,omitempty"`
	CommunityID   int              `json:"community_id" url:"community_id,omitempty"`
	Reason        Optional[string] `json:"reason" url:"reason,omitempty"`
	When          LemmyTime        `json:"when_" url:"when_,omitempty"`
}
type AdminPurgePostForm struct {
	AdminPersonID int              `json:"admin_person_id" url:"admin_person_id,omitempty"`
	CommunityID   int              `json:"community_id" url:"community_id,omitempty"`
	Reason        Optional[string] `json:"reason" url:"reason,omitempty"`
}
type AdminPurgeComment struct {
	ID            int32            `json:"id" url:"id,omitempty"`
	AdminPersonID int              `json:"admin_person_id" url:"admin_person_id,omitempty"`
	PostID        int              `json:"post_id" url:"post_id,omitempty"`
	Reason        Optional[string] `json:"reason" url:"reason,omitempty"`
	When          LemmyTime        `json:"when_" url:"when_,omitempty"`
}
type AdminPurgeCommentForm struct {
	AdminPersonID int              `json:"admin_person_id" url:"admin_person_id,omitempty"`
	PostID        int              `json:"post_id" url:"post_id,omitempty"`
	Reason        Optional[string] `json:"reason" url:"reason,omitempty"`
}
