//  Source: lemmy/crates/api_common/src/websocket/handlers/online_users.rs
// Code generated by go.elara.ws/go-lemmy/cmd/gen (struct generator). DO NOT EDIT.

package types

type GetPostUsersOnline struct {
	PostID int `json:"post_id" url:"post_id,omitempty"`
}
type GetCommunityUsersOnline struct {
	CommunityID int `json:"community_id" url:"community_id,omitempty"`
}
