//  Source: lemmy/crates/db_schema/src/source/person.rs
// Code generated by go.elara.ws/go-lemmy/cmd/gen (struct generator). DO NOT EDIT.

package types

type Person struct {
	ID              int              `json:"id" url:"id,omitempty"`
	Name            string           `json:"name" url:"name,omitempty"`
	DisplayName     Optional[string] `json:"display_name" url:"display_name,omitempty"`
	Avatar          Optional[string] `json:"avatar" url:"avatar,omitempty"`
	Banned          bool             `json:"banned" url:"banned,omitempty"`
	Published       LemmyTime        `json:"published" url:"published,omitempty"`
	Updated         LemmyTime        `json:"updated" url:"updated,omitempty"`
	ActorID         string           `json:"actor_id" url:"actor_id,omitempty"`
	Bio             Optional[string] `json:"bio" url:"bio,omitempty"`
	Local           bool             `json:"local" url:"local,omitempty"`
	PrivateKey      Optional[string] `json:"private_key" url:"private_key,omitempty"`
	PublicKey       string           `json:"public_key" url:"public_key,omitempty"`
	LastRefreshedAt LemmyTime        `json:"last_refreshed_at" url:"last_refreshed_at,omitempty"`
	Banner          Optional[string] `json:"banner" url:"banner,omitempty"`
	Deleted         bool             `json:"deleted" url:"deleted,omitempty"`
	InboxURL        string           `json:"inbox_url" url:"inbox_url,omitempty"`
	SharedInboxURL  Optional[string] `json:"shared_inbox_url" url:"shared_inbox_url,omitempty"`
	MatrixUserID    Optional[string] `json:"matrix_user_id" url:"matrix_user_id,omitempty"`
	Admin           bool             `json:"admin" url:"admin,omitempty"`
	BotAccount      bool             `json:"bot_account" url:"bot_account,omitempty"`
	BanExpires      LemmyTime        `json:"ban_expires" url:"ban_expires,omitempty"`
	InstanceID      int              `json:"instance_id" url:"instance_id,omitempty"`
}
type PersonInsertForm struct {
	Name            string           `json:"name" url:"name,omitempty"`
	PublicKey       string           `json:"public_key" url:"public_key,omitempty"`
	InstanceID      int              `json:"instance_id" url:"instance_id,omitempty"`
	DisplayName     Optional[string] `json:"display_name" url:"display_name,omitempty"`
	Avatar          Optional[string] `json:"avatar" url:"avatar,omitempty"`
	Banned          Optional[bool]   `json:"banned" url:"banned,omitempty"`
	Published       LemmyTime        `json:"published" url:"published,omitempty"`
	Updated         LemmyTime        `json:"updated" url:"updated,omitempty"`
	ActorID         Optional[string] `json:"actor_id" url:"actor_id,omitempty"`
	Bio             Optional[string] `json:"bio" url:"bio,omitempty"`
	Local           Optional[bool]   `json:"local" url:"local,omitempty"`
	PrivateKey      Optional[string] `json:"private_key" url:"private_key,omitempty"`
	LastRefreshedAt LemmyTime        `json:"last_refreshed_at" url:"last_refreshed_at,omitempty"`
	Banner          Optional[string] `json:"banner" url:"banner,omitempty"`
	Deleted         Optional[bool]   `json:"deleted" url:"deleted,omitempty"`
	InboxURL        Optional[string] `json:"inbox_url" url:"inbox_url,omitempty"`
	SharedInboxURL  Optional[string] `json:"shared_inbox_url" url:"shared_inbox_url,omitempty"`
	MatrixUserID    Optional[string] `json:"matrix_user_id" url:"matrix_user_id,omitempty"`
	Admin           Optional[bool]   `json:"admin" url:"admin,omitempty"`
	BotAccount      Optional[bool]   `json:"bot_account" url:"bot_account,omitempty"`
	BanExpires      LemmyTime        `json:"ban_expires" url:"ban_expires,omitempty"`
}
type PersonUpdateForm struct {
	DisplayName     Optional[Optional[string]] `json:"display_name" url:"display_name,omitempty"`
	Avatar          Optional[Optional[string]] `json:"avatar" url:"avatar,omitempty"`
	Banned          Optional[bool]             `json:"banned" url:"banned,omitempty"`
	Updated         LemmyTime                  `json:"updated" url:"updated,omitempty"`
	ActorID         Optional[string]           `json:"actor_id" url:"actor_id,omitempty"`
	Bio             Optional[Optional[string]] `json:"bio" url:"bio,omitempty"`
	Local           Optional[bool]             `json:"local" url:"local,omitempty"`
	PublicKey       Optional[string]           `json:"public_key" url:"public_key,omitempty"`
	PrivateKey      Optional[Optional[string]] `json:"private_key" url:"private_key,omitempty"`
	LastRefreshedAt LemmyTime                  `json:"last_refreshed_at" url:"last_refreshed_at,omitempty"`
	Banner          Optional[Optional[string]] `json:"banner" url:"banner,omitempty"`
	Deleted         Optional[bool]             `json:"deleted" url:"deleted,omitempty"`
	InboxURL        Optional[string]           `json:"inbox_url" url:"inbox_url,omitempty"`
	SharedInboxURL  Optional[Optional[string]] `json:"shared_inbox_url" url:"shared_inbox_url,omitempty"`
	MatrixUserID    Optional[Optional[string]] `json:"matrix_user_id" url:"matrix_user_id,omitempty"`
	Admin           Optional[bool]             `json:"admin" url:"admin,omitempty"`
	BotAccount      Optional[bool]             `json:"bot_account" url:"bot_account,omitempty"`
	BanExpires      LemmyTime                  `json:"ban_expires" url:"ban_expires,omitempty"`
}
type PersonFollower struct {
	ID         int32     `json:"id" url:"id,omitempty"`
	PersonID   int       `json:"person_id" url:"person_id,omitempty"`
	FollowerID int       `json:"follower_id" url:"follower_id,omitempty"`
	Published  LemmyTime `json:"published" url:"published,omitempty"`
	Pending    bool      `json:"pending" url:"pending,omitempty"`
}
type PersonFollowerForm struct {
	PersonID   int  `json:"person_id" url:"person_id,omitempty"`
	FollowerID int  `json:"follower_id" url:"follower_id,omitempty"`
	Pending    bool `json:"pending" url:"pending,omitempty"`
}
