//  Source: lemmy/crates/db_schema/src/source/registration_application.rs
// Code generated by go.arsenm.dev/go-lemmy/cmd/gen (struct generator). DO NOT EDIT.

package types

type RegistrationApplication struct {
	ID          int32            `json:"id" url:"id,omitempty"`
	LocalUserID int              `json:"local_user_id" url:"local_user_id,omitempty"`
	Answer      string           `json:"answer" url:"answer,omitempty"`
	AdminID     Optional[int]    `json:"admin_id" url:"admin_id,omitempty"`
	DenyReason  Optional[string] `json:"deny_reason" url:"deny_reason,omitempty"`
	Published   LemmyTime        `json:"published" url:"published,omitempty"`
}
type RegistrationApplicationInsertForm struct {
	LocalUserID int    `json:"local_user_id" url:"local_user_id,omitempty"`
	Answer      string `json:"answer" url:"answer,omitempty"`
}
type RegistrationApplicationUpdateForm struct {
	AdminID    Optional[Optional[int]]    `json:"admin_id" url:"admin_id,omitempty"`
	DenyReason Optional[Optional[string]] `json:"deny_reason" url:"deny_reason,omitempty"`
}
