//  Source: lemmy/crates/db_views_moderator/src/structs.rs
// Code generated by go.elara.ws/go-lemmy/cmd/gen (struct generator). DO NOT EDIT.

package types

type ModAddCommunityView struct {
	ModAddCommunity ModAddCommunity      `json:"mod_add_community" url:"mod_add_community,omitempty"`
	Moderator       Optional[PersonSafe] `json:"moderator" url:"moderator,omitempty"`
	Community       CommunitySafe        `json:"community" url:"community,omitempty"`
	ModdedPerson    PersonSafe           `json:"modded_person" url:"modded_person,omitempty"`
}
type ModAddView struct {
	ModAdd       ModAdd               `json:"mod_add" url:"mod_add,omitempty"`
	Moderator    Optional[PersonSafe] `json:"moderator" url:"moderator,omitempty"`
	ModdedPerson PersonSafe           `json:"modded_person" url:"modded_person,omitempty"`
}
type ModBanFromCommunityView struct {
	ModBanFromCommunity ModBanFromCommunity  `json:"mod_ban_from_community" url:"mod_ban_from_community,omitempty"`
	Moderator           Optional[PersonSafe] `json:"moderator" url:"moderator,omitempty"`
	Community           CommunitySafe        `json:"community" url:"community,omitempty"`
	BannedPerson        PersonSafe           `json:"banned_person" url:"banned_person,omitempty"`
}
type ModBanView struct {
	ModBan       ModBan               `json:"mod_ban" url:"mod_ban,omitempty"`
	Moderator    Optional[PersonSafe] `json:"moderator" url:"moderator,omitempty"`
	BannedPerson PersonSafe           `json:"banned_person" url:"banned_person,omitempty"`
}
type ModHideCommunityView struct {
	ModHideCommunity ModHideCommunity     `json:"mod_hide_community" url:"mod_hide_community,omitempty"`
	Admin            Optional[PersonSafe] `json:"admin" url:"admin,omitempty"`
	Community        CommunitySafe        `json:"community" url:"community,omitempty"`
}
type ModLockPostView struct {
	ModLockPost ModLockPost          `json:"mod_lock_post" url:"mod_lock_post,omitempty"`
	Moderator   Optional[PersonSafe] `json:"moderator" url:"moderator,omitempty"`
	Post        Post                 `json:"post" url:"post,omitempty"`
	Community   CommunitySafe        `json:"community" url:"community,omitempty"`
}
type ModRemoveCommentView struct {
	ModRemoveComment ModRemoveComment     `json:"mod_remove_comment" url:"mod_remove_comment,omitempty"`
	Moderator        Optional[PersonSafe] `json:"moderator" url:"moderator,omitempty"`
	Comment          Comment              `json:"comment" url:"comment,omitempty"`
	Commenter        PersonSafe           `json:"commenter" url:"commenter,omitempty"`
	Post             Post                 `json:"post" url:"post,omitempty"`
	Community        CommunitySafe        `json:"community" url:"community,omitempty"`
}
type ModRemoveCommunityView struct {
	ModRemoveCommunity ModRemoveCommunity   `json:"mod_remove_community" url:"mod_remove_community,omitempty"`
	Moderator          Optional[PersonSafe] `json:"moderator" url:"moderator,omitempty"`
	Community          CommunitySafe        `json:"community" url:"community,omitempty"`
}
type ModRemovePostView struct {
	ModRemovePost ModRemovePost        `json:"mod_remove_post" url:"mod_remove_post,omitempty"`
	Moderator     Optional[PersonSafe] `json:"moderator" url:"moderator,omitempty"`
	Post          Post                 `json:"post" url:"post,omitempty"`
	Community     CommunitySafe        `json:"community" url:"community,omitempty"`
}
type ModFeaturePostView struct {
	ModFeaturePost ModFeaturePost       `json:"mod_feature_post" url:"mod_feature_post,omitempty"`
	Moderator      Optional[PersonSafe] `json:"moderator" url:"moderator,omitempty"`
	Post           Post                 `json:"post" url:"post,omitempty"`
	Community      CommunitySafe        `json:"community" url:"community,omitempty"`
}
type ModTransferCommunityView struct {
	ModTransferCommunity ModTransferCommunity `json:"mod_transfer_community" url:"mod_transfer_community,omitempty"`
	Moderator            Optional[PersonSafe] `json:"moderator" url:"moderator,omitempty"`
	Community            CommunitySafe        `json:"community" url:"community,omitempty"`
	ModdedPerson         PersonSafe           `json:"modded_person" url:"modded_person,omitempty"`
}
type AdminPurgeCommentView struct {
	AdminPurgeComment AdminPurgeComment    `json:"admin_purge_comment" url:"admin_purge_comment,omitempty"`
	Admin             Optional[PersonSafe] `json:"admin" url:"admin,omitempty"`
	Post              Post                 `json:"post" url:"post,omitempty"`
}
type AdminPurgeCommunityView struct {
	AdminPurgeCommunity AdminPurgeCommunity  `json:"admin_purge_community" url:"admin_purge_community,omitempty"`
	Admin               Optional[PersonSafe] `json:"admin" url:"admin,omitempty"`
}
type AdminPurgePersonView struct {
	AdminPurgePerson AdminPurgePerson     `json:"admin_purge_person" url:"admin_purge_person,omitempty"`
	Admin            Optional[PersonSafe] `json:"admin" url:"admin,omitempty"`
}
type AdminPurgePostView struct {
	AdminPurgePost AdminPurgePost       `json:"admin_purge_post" url:"admin_purge_post,omitempty"`
	Admin          Optional[PersonSafe] `json:"admin" url:"admin,omitempty"`
	Community      CommunitySafe        `json:"community" url:"community,omitempty"`
}
type ModlogListParams struct {
	CommunityID     Optional[int]   `json:"community_id" url:"community_id,omitempty"`
	ModPersonID     Optional[int]   `json:"mod_person_id" url:"mod_person_id,omitempty"`
	OtherPersonID   Optional[int]   `json:"other_person_id" url:"other_person_id,omitempty"`
	Page            Optional[int64] `json:"page" url:"page,omitempty"`
	Limit           Optional[int64] `json:"limit" url:"limit,omitempty"`
	HideModlogNames bool            `json:"hide_modlog_names" url:"hide_modlog_names,omitempty"`
}
