//  Source: lemmy/crates/api_common/src/utils.rs
// Code generated by go.elara.ws/go-lemmy/cmd/gen (struct generator). DO NOT EDIT.

package types

type EndpointType string

const (
	EndpointTypeCommunity      EndpointType = "Community"
	EndpointTypePerson         EndpointType = "Person"
	EndpointTypePost           EndpointType = "Post"
	EndpointTypeComment        EndpointType = "Comment"
	EndpointTypePrivateMessage EndpointType = "PrivateMessage"
)
